
# .travis.yaml
#
# This file is part of NEST.
#
# Copyright (C) 2004 The NEST Initiative
#
# NEST is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# NEST is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NEST.  If not, see <http://www.gnu.org/licenses/>.


# This is the Travis CI top-level script to setup and run the NEST
# build and test environment.

language: python

services:
  - docker

cache:
  directories:
  - docker-image

install:
  - docker pull nestsim/nest:builder
  - docker save nestsim/nest:builder | gzip docker-image/nest-builder.tar.gz

before_script:
- gzip -dc docker-image/nest-builder.tar.gz | docker load
#env:
#  - FOO=foo
#  - FOO=bar

jobs:
  include:
    - stage: "Tests"                # naming the Tests stage
      name: "Unit Tests"            # names the first Tests stage job
      script: docker run -it --rm -v $(pwd):/opt/data nestsim/nest:builder build
    - script: docker run -it --rm -v $(pwd):/opt/data nestsim/nest:builder build
      name: "Integration Tests"     # names the second Tests stage job
    - stage: linear
      name: "Not parallel"
      script: docker run -it --rm -v $(pwd):/opt/data nestsim/nest:builder build
